### ISSUE TITLE
Exception occured while evaluating the Product Check action 

### ISSUE THREAD

**Issue by rehammuzzamil** [OpenSRP/opensrp-plan-evaluator#118]
```
Caused by: java.lang.IllegalStateException: Trimmed String value length: 0 is less than minimum required length: 1
	at com.ibm.fhir.model.util.ValidationSupport.checkString(ValidationSupport.java:101)
	at com.ibm.fhir.model.type.String.<init>(String.java:29)
	at com.ibm.fhir.model.type.String$Builder.build(String.java:197)
	at com.ibm.fhir.model.type.String.of(String.java:54)
	at org.smartregister.converters.StockConverter.convertStockToBundleResource(StockConverter.java:51)

```
- Add if check to avoid setting serial number in the Bundle Resource when it is an empty string
- Related to https://github.com/OpenSRP/opensrp-server-web/issues/728 . Product check tasks are not being generated due to this issue.

cc: @bennsimon  @githengi

**Comment by rehammuzzamil** [comment]
Reopened for QA.

**Comment by cafootitt** [comment]
In summary, this issue was being caused by 3 things:

- Plan Evaluator Serial Number Bug prevented product tasks to be created ... has been fixed here https://github.com/OpenSRP/opensrp-plan-evaluator/issues/118
- Product Check action missed in the plan being used.
- Update plan only triggers planEvaluation when jurisdictions are modified
